files:
  # Libraries
  - bower_components/jquery/jquery.js
  - bower_components/underscore/underscore.js
  - bower_components/backbone/backbone.js
  - bower_components/marionette/lib/backbone.marionette.js

  - bower_components/flot/jquery.flot.js

  # Templates
  - _tmp/templates.js

  # Application
  - backbone/settings.js
  - backbone/application.js
  - backbone/config/backbone/sync.js
  - backbone/controllers/*.js
  - backbone/entities/*.js
  - backbone/apps/**/*.js
